### ISSUE TITLE
Method assert not found?

### ISSUE THREAD

**Issue by ghost** [popphp/pop-acl#2]
After a long time I put my hand back to this framework.

To program use PHPStorm that tells me some problems.

In the Acl component it tells me that the assert () method is missing, which is also defined by the AssertionInterface interface but not implemented.

Then tell me if it's a wanted behavior?

Thank you.

**Comment by nicksagona** [comment]
Yes this is correct. The AssertionInterface is a "template" interface that someone can use if they want to have a finer amount of control in evaluating permissions. So there is no class shipped with the pop-acl component that implements the AssertionInterface. You would create one yourself and write the assert method you need. From there, your custom Assertion object can be injected into one of the main "allow" or "deny" methods of the main Acl object like (4th parameter):
```php
public function allow($role, $resource = null, $permission = null, AssertionInterface $assertion = null) 
```
If you're getting the error that the assert() method is missing then you might have set it up incorrectly.
There's a small example in the docs here: http://docs.popphp.org/en/latest/reference/pop_acl.html#assertions

**Comment by ghost** [comment]
Thanks for the reply. I was wrong in my trial implementation.

**Comment by nicksagona** [comment]
No problem - thanks for your interest in Pop PHP!
